### ISSUE TITLE
Category and tag improvement

### ISSUE THREAD

**Issue by h4n5h4n5** [rstammer/kneipenquiz#11]
Bei Neuanlegen einer Frage wird die Kategorie nicht übernommen. Dies geschieht erst bei Bearbeitung, allerdings zeigt das Pulldownmenü der Fragentypen dann "normal" und nicht den bereits veränderten Typus an, was ihn bei Unachtsamkeit wieder zurücksetzt.

**Comment by rstammer** [comment]
Ok, das wird gefixt! :wrench:
