### ISSUE TITLE
Javascript and button design for mobile

### ISSUE THREAD

**Issue by h4n5h4n5** [rstammer/kneipenquiz#5]
JS interpretation on mobile devices (answer button).

**Comment by h4n5h4n5** [comment]
Button funktioniert auch nicht in Desktop-Chrome.

**Comment by rstammer** [comment]
Was meinst Du genau mit 'Button funktioniert nicht' ?

**Comment by h4n5h4n5** [comment]
Ich meinte: Mausklick auf Button erzeugt Farbänderung des Buttons, aber jetzt funktioniert's. :)

Grüße
—

**Comment by rstammer** [comment]
Oki!
