### ISSUE TITLE
Increase character limit

### ISSUE THREAD

**Issue by h4n5h4n5** [rstammer/kneipenquiz#6]
Es sind nur 255 Zeichen zugelassen - ist für einige Fragen ein Bisschen zu wenig - auch sollte die Anzeigeschrift der Frage etwas kleiner sein.

**Comment by rstammer** [comment]
Ich habe das noch ein wenig Erweitert. Zunächst: Klar, 255 war zu sparsam, jetzt darf es gerne mehr sein. Habe aber auch ein zusätzliches Feld 'Einführungstext' draufgelegt. Dann kann man die Fragestory und die Frage selbst trennen. How about that?

**Comment by h4n5h4n5** [comment]
Ja, sehr gut - der Einführungstext könnte aber einen Tick größer sein.—
