### ISSUE TITLE
Split questions in upcoming, later and already used

### ISSUE THREAD

**Issue by h4n5h4n5** [rstammer/kneipenquiz#8]
z.B. durch Schriftfarbe des Fragentitels in Fragenübersicht (rot - für's nächste Quiz, blau - für irgendwann und grau - bereits verwendet; diese sollten dann auch ans Ende der Übersicht rutschen)

**Comment by rstammer** [comment]
Ich würde vorschlagen, für diese Aufgabe die Tags zu benutzen. D.h. entsprechende Tags zu benutzen. Dazu würde ich dann das Tag-System erweitern...

**Comment by h4n5h4n5** [comment]
Ja, das wäre auch eine Möglichkeit.
